### ISSUE TITLE
ble server example watchdog

### ISSUE THREAD

**Issue by Lance-Kraakman** [taks/esp32-nimble#11]
Hi just a quick question, 

Why is the watchdog timer turned off in the ble server example?
Also i'm happy to work on any minor tasks if you guys need something done!

Thanks!

**Comment by taks** [comment]
I was turning off the watchdog because I was using `esp_idf_hal::delay::Ets::delay_ms` inside the loop.
( `esp_idf_hal::delay::Ets::delay_ms` does not clear the watchdog timer. )

I remove the code to turn off the watchdog timer by using `esp_idf_hal::delay::FreeRtos::delay_ms`
which clears the watchdog timer.

**Comment by Lance-Kraakman** [comment]
No worries :) thank you!
